<?php 
$exchanges = $data['exchanges'];
$user = $data['currentUser']; 
?>

<h2><?php $l->e("Offene Tausche"); ?></h2>
<div class="exchange-list">
	<?php 
		if (count($exchanges[$data['active_key']]) > 0) {
			
			foreach ($exchanges[$data['active_key']] as $info) {
				$exchange = $info['exchange'];
				$step = $info['currentStep'];
		?>
		<div class="exchange showexchange" data-id="<?php echo $exchange->getId(); ?>">
			<div class="exchangeImage" style="background-image:url('<?php echo $exchange->getSteps()[0]->getArticles()[0]->getImage(); ?>')">
			</div>
			<div class="exchangeinfo">
				<div class="name">
					<?php $l->e("Nutzer");?>:
						<br />
					<?php 
						if ($exchange->getRequestingUser()->getId() == $user->getId()) {
							echo $exchange->getAnsweringUser()->getUsername(); 
						?>
							<br /><br />
						<?php $l->e("Status"); ?>:
							<br />
						<?php 
							if ($step->getType() == $data['pick_key']) {
								$l->e("Angebot oder Gegenangebot vorhanden");
							} else {
								$l->e("Warte auf Antwort");
							}
						 } else {
						 	echo $exchange->getRequestingUser()->getUsername();
				 		?>
				 			<br />
	 					<?php $l->e("Status"); ?>:
	 					<?php 
						 	if ($step->getType() == $data['request_key'] || $step->getType() == $data['reoffer_key']) {
						 		$l->e("Angebot oder Gegenangebot vorhanden");
						 	} else {
						 		$l->e("Warte auf Antwort");
						 	}
						 }
					?>
				</div>
			</div>
		</div>
		<?php 
			}
		?>
		<div class="clearfix"></div>
	<?php 
		} else {
	?>
		<h3><?php $l->e("Keine Tausche"); ?></h3>
	<?php
		}
	?>	
</div>
<h2><?php $l->e("Abgebrochene Tausche")?></h2>
<div class="exchange-list">
	<?php 
		if (count($exchanges[$data['cancelled_key']]) > 0) {
			foreach ($exchanges[$data['cancelled_key']] as $info) {
				$exchange = $info['exchange'];
				$step = $info['currentStep'];
		?>
		<div class="exchange" data-id="<?php echo $exchange->getId(); ?>">
			<div class="exchangeImage" style="background-image:url('<?php echo $exchange->getSteps()[0]->getArticles()[0]->getImage(); ?>')">
			</div>
			<div class="exchangeinfo">
				<div class="name">
					<?php 
						$l->e("Nutzer");
						?>: <?php 
						if ($exchange->getRequestingUser()->getId() == $user->getId()) {
							echo $exchange->getAnsweringUser()->getUsername(); 
						} else {
							echo $exchange->getRequestingUser()->getUsername();
						}
					?>
				</div>
			</div>
		</div>
		<?php 
			}
		?>
		<div class="clearfix"></div>
	<?php 
		} else {
	?>
		<h3><?php $l->e("Keine Tausche"); ?></h3>
	<?php
		}
	?>
</div>
<h2><?php $l->e("Abgeschlossene Tausche")?></h2>
<div class="exchange-list">
	<?php
		if (count($exchanges[$data['completed_key']]) > 0) {	
			foreach ($exchanges[$data['completed_key']] as $info) {
				$exchange = $info['exchange'];
				$step = $info['currentStep'];
		?>
		<div class="exchange" data-id="<?php echo $exchange->getId(); ?>">
			<div class="exchangeImage" style="background-image:url('<?php echo $exchange->getSteps()[0]->getArticles()[0]->getImage(); ?>')">
			</div>
			<div class="exchangeinfo">
				<div class="name">
					<?php 
						$l->e("Nutzer");
						?>: <?php
						if ($exchange->getRequestingUser()->getId() == $user->getId()) {
							echo $exchange->getAnsweringUser()->getUsername(); 
						} else {
							echo $exchange->getRequestingUser()->getUsername();
						}
					?>
				</div>
			</div>
		</div>
		<?php 
			}
		?>
		<div class="clearfix"></div>
	<?php 
		} else {
	?>
		<h3><?php $l->e("Keine Tausche"); ?></h3>
	<?php
		}
	?>
</div>