<div class="product-list">
	
<?php
	/* @var $article Application\Models\Db\Article2 */ 
	foreach($data['articles'] as $article) { 
?>
	<div class="product">
		<a href="/product/detail/item/<?php echo $article->getId(); ?>">
			<img src="data:image/jpeg;base64,<?php echo base64_encode($article->getImage()); ?>" />
			<div class="productinfo">
				<div class="name">
					<?php echo $article->getName(); ?>
				</div>
<!-- 				<div class="location"> -->
					<?php //echo $article->getLocationId(); ?>
<!-- 				</div> -->
			</div>
		</a>
	</div>
<?php 
}
?>
</div>