<div class="product-list">
	
<?php
	/* @var $article Application\Models\Db\Article2 */ 
	foreach($data['articles'] as $article) { 
?>
	<div class="product">
		<a href="/article/show/item/<?php echo $article->getId(); ?>">
			<img src="/article/getimage/id/<?php echo $article->getId(); ?>" />
			<div class="productinfo">
				<div class="name">
					<?php echo $article->getName(); ?>
				</div>
<!-- 				<div class="location"> -->
					<?php //echo $article->getLocationId(); ?>
<!-- 				</div> -->
			</div>
		</a>
	</div>
<?php 
}
?>
</div>