<?php 
/* @var $article Application\Models\DB\Article2 */
$article = $data['article'];
$location = $data['location'];
$user = $data['user'];
?>

<div class="product-detail">
	<div class="formLeft">
		<h1><?php echo $article->getName(); ?></h1>
		<h2><?php echo $l->e('Beschreibung');?></h2>
		<div class="decription">
			<?php echo $article->getDescription(); ?>
		</div>	
		<h2><?php echo $l->e('Kategorien');?></h2>
		<ul class="categorieList">
		<?php foreach($article->getCategories() as $cat) {?>
			<li><?php echo $cat->getName();?></li>
		<?php }?>
		</ul>
		<?php if ($location != null) { ?>
		<h2><?php echo $l->e('Adresse Besitzer');?></h2>
		<ul>
			<li><?php echo $l->e('Benutzer: ');?> <?php echo $user->getUsername();?></li>
			<li><?php echo $l->e('Strasse: ');?> <?php echo $location->getStreet();?></li>
			<li><?php echo $l->e('PLZ: ');?> <?php echo $location->getPostcode();?></li>
			<li><?php echo $l->e('Ort: ');?> <?php echo $location->getTown();?></li>
			
		</ul>
		<?php } ?>
		<h2><?php $l->e("Tauschen oder Ausleihen")?></h2>
		<div class="exchangeContainer">
			<form action="" method="post" id="exchangeForm">	
				<textarea style="height:60px;" name="exchangeRemark" placeholder="<?php $l->e("Bemerkung"); ?>"></textarea>
				<input type="submit" class="singleButton" name="exchangeBorrow" id="exchangeBorrowButton" value="<?php $l->e("Ausleihen") ?>" />
				<input type="submit" class="singleButton" name="exchangeExchange" id="exchangeExchangeButton" value="<?php $l->e("Tauschen") ?>" />
				<input type="hidden" name="exchangeArticle" value="<?php echo $article->getId(); ?>" />
			</form>
		</div>
	</div>
	<div class="formRight">
		<div class="imageContainer">
			<img src="<?php echo $article->getImage(); ?>" />
		</div>	
	</div>

</div>
