<?php 
/* @var $article Application\Models\DB\Article2 */
$article = $data['article'];
$location = $data['location'];
$user = $data['user'];
?>

<div class="product-detail">
	<div class="formLeft">
		<h1><?php echo $article->getName(); ?></h1>
		<h2><?php echo $l->e('Beschreibung');?></h2>
		<div class="decription">
			<?php echo $article->getDescription(); ?>
		</div>	
		<h2><?php echo $l->e('Kategorien');?></h2>
		<ul class="categorieList">
		<?php foreach($article->getCategories() as $cat) {?>
			<li><?php echo $cat->getName();?></li>
		<?php }?>
		</ul>
		<?php if ($location != null) {?>
		<h2><?php echo $l->e('Adresse Besitzer');?></h2>
		<ul>
			<li><?php echo $l->e('Benutzer: ');?> <?php echo $user->getUsername();?></li>
			<li><?php echo $l->e('Strasse: ');?> <?php echo $location->getStreet();?></li>
			<li><?php echo $l->e('PLZ: ');?> <?php echo $location->getPostcode();?></li>
			<li><?php echo $l->e('Ort: ');?> <?php echo $location->getTown();?></li>
			
		</ul>
		<?php } ?>
	</div>
	<div class="formRight">
		<div class="imageContainer">
			<img src="<?php echo $article->getImage(); ?>" />
		</div>	
		<div class="exchangeContainer">
			<h2><?php $l->e("Produkt anfragen"); ?></h2>
			<div class="exchangeForm">
				<div class="input-wrapper">
					<label for="exchange_remark"><?php $l->e("Bemerkung"); ?></label> 
					<textarea name="exchange_remark" placeholder="<?php $l->e("Bemerkung"); ?>"></textarea>
				</div>
				<div class="input-wrapper">
					<input type="submit" class="button" name="submit" value="<?php $l->e("Absenden"); ?>">
				</div>
			</div>
		</div>
	</div>

</div>
