<ul class="level-1">
	<li>
		<a href="/article/upload/">
			<span><?php echo $l->e('Neuer Artikel erstellen');?></span>
		</a>
	</li>
	<li>
		<a href="/article/userlist/">
			<span><?php echo $l->e('Meine Produkte');?></span>
		</a>
	</li>
	<li>
		<a href="/exchange/list">
			<span><?php echo $l->e('Meine Verhandlungen');?></span>
		</a>
	</li>
	<li>
		<a href="/auth/logout/">
			<span><?php echo $l->e('Abmelden');?></span>
		</a>
	</li>
</ul>