<ul class="level-1">
	<li>
		<a href="/article/upload/">
			<span><?php echo $l->e('Neuen Artikel erstellen');?></span>
		</a>
	</li>
	<li>
		<a href="/article/userlist/">
			<span><?php echo $l->e('Meine Produkte');?></span>
		</a>
	</li>
	<li>
		<a href="/exchange/listborrow">
			<span><?php echo $l->e('Meine Ausleihen');?></span>
		</a>
	</li>
	<li>
		<a href="/exchange/listexchange">
			<span><?php echo $l->e('Meine Tausche');?></span>
		</a>
	</li>
	<li>
		<a href="/auth/profile">
			<span><?php echo $l->e('Mein Profil');?></span>
		</a>
		<ul class="level-2" <?php if ($data['profile']) { ?>style="display:block;"<?php }?>>
			<li>
				<a href="/auth/password">
					<span><?php echo $l->e('Passwort ändern');?></span>
				</a>
			</li>	
		</ul>
	</li>
	<li>
		<a href="/auth/logout/">
			<span><?php echo $l->e('Abmelden');?></span>
		</a>
	</li>
</ul>