<?php 
/* @var $article Application\Models\DB\Article2 */
$parentCategories = $data['parentCategories'];
$childCategories = $data['childCategories'];

?>
<span>
	<?php echo $l->e('Gefundene Kategorien'); ?>
</span>
<ul class="level-1">
<?php foreach( $parentCategories as $parCat) {?>
	<li>
		<span data-id="<?php echo $parCat->getId(); ?>"><?php echo $parCat->getName(); ?></span>
		<ul class="level-2" toggled="false">
			<?php foreach( $childCategories as $childCat) {
				if ($childCat->getParentId() == $parCat->getId()) {
			?>
					<li><span data-id="<?php echo $childCat->getId(); ?>"><?php echo $childCat->getName(); ?></span></li>	
			<?php
				} 
			} ?>
		</ul>
	</li>
<?php } ?>
</ul>