-- MySQL Script generated by MySQL Workbench
-- 12/05/14 11:37:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shareshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shareshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shareshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `shareshop` ;

-- -----------------------------------------------------
-- Table `shareshop`.`sha_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shareshop`.`sha_category` ;

CREATE TABLE IF NOT EXISTS `shareshop`.`sha_category` (
  `cat_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(255) NOT NULL,
  `cat_parent_id` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`cat_id`),
  INDEX `sha_cat_cat_idx` (`cat_parent_id` ASC),
  CONSTRAINT `sha_cat_cat`
    FOREIGN KEY (`cat_parent_id`)
    REFERENCES `shareshop`.`sha_category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shareshop`.`sha_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shareshop`.`sha_location` ;

CREATE TABLE IF NOT EXISTS `shareshop`.`sha_location` (
  `loc_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `loc_street` VARCHAR(255) NOT NULL,
  `loc_houseNumber` VARCHAR(10) NOT NULL,
  `loc_zip_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`loc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shareshop`.`sha_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shareshop`.`sha_user` ;

CREATE TABLE IF NOT EXISTS `shareshop`.`sha_user` (
  `usr_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usr_username` VARCHAR(255) NOT NULL,
  `usr_password` CHAR(32) NOT NULL COMMENT 'http://stackoverflow.com/questions/247304/what-data-type-to-use-for-hashed-password-field-and-what-length',
  `usr_loc_id` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`usr_id`),
  UNIQUE INDEX `username_UNIQUE` (`usr_username` ASC),
  INDEX `sha_fk_usr_loc_idx` (`usr_loc_id` ASC),
  CONSTRAINT `sha_fk_usr_loc`
    FOREIGN KEY (`usr_loc_id`)
    REFERENCES `shareshop`.`sha_location` (`loc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shareshop`.`sha_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shareshop`.`sha_article` ;

CREATE TABLE IF NOT EXISTS `shareshop`.`sha_article` (
  `art_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `art_name` VARCHAR(255) NOT NULL,
  `art_description` VARCHAR(1000) NOT NULL,
  `art_image` VARCHAR(255) NULL,
  `art_usr_id` INT(10) UNSIGNED NOT NULL,
  `art_cat_id` INT(10) UNSIGNED NOT NULL,
  `art_creation_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`art_id`),
  INDEX `sha_fk_art_cat_idx` (`art_cat_id` ASC),
  INDEX `sha_fk_art_usr_idx` (`art_usr_id` ASC),
  CONSTRAINT `sha_fk_art_cat`
    FOREIGN KEY (`art_cat_id`)
    REFERENCES `shareshop`.`sha_category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sha_fk_art_usr`
    FOREIGN KEY (`art_usr_id`)
    REFERENCES `shareshop`.`sha_user` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
