<div class="product-list">
	<div class="product">
		<a href="detail.htm">
			<img src="./images/product.jpg" />
			<div class="productinfo">
				<div class="name">
					Name
				</div>
				<div class="location">
					Ort
				</div>
			</div>
		</a>
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>					
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
	<div class="product">
		<img src="./images/product.jpg" />
	</div>
</div>