<div class="product-list">
	
<?php
	/* @var $article Application\Models\Db\Article2 */ 
	foreach($data['articles'] as $article) { 
?>
	<div class="product">
		<a href="/index/detail/item/<?php echo $article->getId(); ?>">
			<img src="/images/product.jpg" />
			<div class="productinfo">
				<div class="name">
					<?php echo $article->getName(); ?>
				</div>
				<div class="location">
					<?php echo $article->getLocationId(); ?>
				</div>
			</div>
		</a>
	</div>
<?php 
}
?>
</div>