<div class="product-upload">
	<h1>Anmeldung erforderlich</h1>
	<h3 class="error">
		<?php echo $data['error']; ?>
	</h3>
	<div class="formLeft">
		<h2>
			Bitte melde dich an.
		</h2>
		<form method="post" accept-charset="utf-8">
			<div class="input-wrapper">
				<label for="username">Benutzername</label>
				<input type="text" id="username" name="username" placeholder="Benutzername" />
			</div>
			<div class="input-wrapper">
				<label for="password">Passwort</label>
				<input type="password" id="password" name="password" placeholder="Passwort">
			</div>
			<div class="input-wrapper">
				<input type="submit" class="singleButton" name="submitLogin" value="Anmelden">
			</div>
		</form>	
	</div>
	<div class="formRight">
		<h2>
			Noch nicht registriert?
		</h2>
		<form action="/Auth/register" method="post" accept-charset="utf-8" id="registerForm">
			<div class="input-wrapper">
				<label for="username">Benutzername</label>
				<input type="text" id="username" name="username" placeholder="Benutzername" />
			</div>
			<div class="input-wrapper">
				<label for="password">Passwort</label>
				<input type="password" id="password" name="password" placeholder="Passwort">
			</div>
			<div class="input-wrapper">
				<label for="passwordRepeat">Passwort wiederholen</label>
				<input type="password" id="passwordRepeat" name="passwordRepeat" placeholder="Passwort wiederholen">
			</div>
			<div class="input-wrapper">
				<label for="email">E-Mail</label>
				<input type="text" id="email" name="email" placeholder="example@example.com">
			</div>
			<div class="input-wrapper">
				<label for="adresse" onkeyup="codeAddress()">Adresse</label>
				<input type="text" id="adresse" name="adresse" placeholder="Mustergasse 3, 1000 Musterstadt">
			</div>
			
			<div id="map-canvas" ></div>
			<input id="person_lat" name="person[lat]" value="<?php echo $data['form']['person_lat']; ?>" type="hidden">
			<input id="person_lng" name="person[lng]" value="<?php echo $data['form']['person_lng']; ?>" type="hidden">
			
			<div class="input-wrapper">
				<input type="submit" class="singleButton" name="submitRegister" value="Registrieren">
			</div>
			
			
		</form>
	</div>
	<div class="clearFix">
	</div>
	
</div>