<div class="product-upload">
	<h1><?php $l->e("Passwort ändern"); ?></h1>
	<h3 class="error">
		<?php $l->e($data['error']); ?>
	</h3>
	<?php if (!empty($data['success'])) { ?>
	<h3 class="success">
		<?php $l->e($data['success']); ?>
	</h3>
	<?php } ?>
	<form action="/auth/password" method="post" accept-charset="utf-8" id="registerForm">
		<div class="input-wrapper">
			<label for="oldPassword"><?php $l->e("Bisheriges Passwort"); ?></label>
			<input type="password" id="password" name="oldPassword" placeholder="<?php $l->e("Bisheriges Passwort"); ?>">
		</div>
		<div class="input-wrapper">
			<label for="password"><?php $l->e("Passwort"); ?></label>
			<input type="password" id="password" name="password" placeholder="<?php $l->e("Passwort"); ?>">
		</div>
		<div class="input-wrapper">
			<label for="passwordRepeat"><?php $l->e("Passwort wiederholen"); ?></label>
			<input type="password" id="passwordRepeat" name="passwordRepeat" placeholder="<?php $l->e("Passwort wiederholen"); ?>">
		</div>
		<div class="input-wrapper">
			<input type="submit" class="singleButton" name="submitRegister" value="<?php $l->e("Absenden"); ?>">
		</div>
	</form>
</div>