<div class="product-upload">
	<h1><?php $l->e("Profil anpassen"); ?></h1>
	<h3 class="error">
		<?php echo $data['error']; ?>
	</h3>
	<?php if (!empty($data['success'])) { ?>
	<h3 class="success">
		<?php echo $data['success']; ?>
	</h3>
	<?php } ?>
	<form action="/auth/profile" method="post" accept-charset="utf-8" id="registerForm">
		<div class="input-wrapper">
			<label for="language"><?php $l->e("Sprache"); ?></label>
			<select name="language">
				<option value="de_de" <?php if ($data['form']['language'] == 'de_de') { ?> selected="selected" <?php } ?>>Deutsch</option>
				<option value="en_us" <?php if ($data['form']['language'] != 'de_de') { ?> selected="selected" <?php } ?>>English</option>
			</select>
		</div>
		<div class="input-wrapper">
			<label for="email"><?php $l->e("E-Mail"); ?></label>
			<input type="text" id="email" name="email" placeholder="example@example.com" value="<?php echo $data['form']['email']; ?>">
		</div>
		<div class="input-wrapper">
			<label for="adresse" onkeyup="codeAddress()"><?php $l->e("Adresse"); ?></label>
			<input type="text" id="adresse" name="adresse" placeholder="Mustergasse 3, 1000 Musterstadt" value="<?php echo $data['form']['adresse']; ?>">
		</div>
		<script type="text/javascript">
			console.log('inline js');
			codeAddress();
		</script>
		<div id="map-canvas" ></div>
		<input id="adresse_lat" name="adresse_lat" value="<?php echo $data['form']['adresse_lat']; ?>" type="hidden">
		<input id="adresse_lng" name="adresse_lng" value="<?php echo $data['form']['adresse_lng']; ?>" type="hidden">

		
		<div class="input-wrapper">
			<input type="submit" class="singleButton" name="submitRegister" value="<?php $l->e("Absenden"); ?>">
		</div>
	</form>
</div>