<div class="product-upload">
	<h1><?php $l->e("Registrierung"); ?></h1>
	<h3 class="error">
		<?php $l->e($data['error']); ?>
	</h3>
	<?php if (!empty($data['success'])) { ?>
	<h3 class="success">
		<?php $l->e($data['success']); ?>
	</h3>
	<?php } else { ?>
	<h2>
		<?php $l->e("Jetzt hier registrieren"); ?>
	</h2>
	<form action="/auth/register" method="post" accept-charset="utf-8" id="registerForm">
		<div class="input-wrapper">
			<label for="username"><?php $l->e("Benutzername"); ?></label>
			<input type="text" id="username" name="username" placeholder="<?php $l->e("Benutzername"); ?>" value="<?php echo $data['form']['username']; ?>"/>
		</div>
		<div class="input-wrapper">
			<label for="password"><?php $l->e("Passwort"); ?></label>
			<input type="password" id="password" name="password" placeholder="<?php $l->e("Passwort"); ?>">
		</div>
		<div class="input-wrapper">
			<label for="passwordRepeat"><?php $l->e("Passwort wiederholen"); ?></label>
			<input type="password" id="passwordRepeat" name="passwordRepeat" placeholder="<?php $l->e("Passwort wiederholen"); ?>">
		</div>
		<div class="input-wrapper">
			<label for="language"><?php $l->e("Sprache"); ?></label>
			<select name="language">
				<option value="de_de" <?php if ($data['form']['language'] == 'de_de') { ?> selected="selected" <?php } ?>>Deutsch</option>
				<option value="en_us" <?php if ($data['form']['language'] != 'de_de') { ?> selected="selected" <?php } ?>>English</option>
			</select>
		</div>
		<div class="input-wrapper">
			<label for="email"><?php $l->e("E-Mail"); ?></label>
			<input type="text" id="email" name="email" placeholder="example@example.com" value="<?php echo $data['form']['email']; ?>">
		</div>
		<div class="input-wrapper">
			<label for="adresse" onkeyup="codeAddress()"><?php $l->e("Adresse"); ?></label>
			<input type="text" id="adresse" name="adresse" placeholder="<?php $l->e("Mustergasse 3, 1000 Musterstadt"); ?>" value="<?php echo $data['form']['adresse']; ?>">
		</div>
		
		<div id="map-canvas" ></div>
		<input id="adresse_lat" name="adresse_lat" value="<?php echo $data['form']['adresse_lat']; ?>" type="hidden">
		<input id="adresse_lng" name="adresse_lng" value="<?php echo $data['form']['adresse_lng']; ?>" type="hidden">
		
		
		<div class="input-wrapper">
			<input type="submit" class="singleButton" name="submitRegister" value="<?php $l->e("Registrieren"); ?>">
		</div>
	</form>

	<?php } ?>
</div>