<!DOCTYPE html>
<html>
<head>
	<title>Unser Webshop</title>
	<link rel="stylesheet" href="/css/reset.css">
	<link rel="stylesheet" href="/css/css.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
	<script src="/js/js.js" type="text/javascript" charset="utf-8" async defer></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
</head>
<body>
	<div id="page">
		<div id="header">
			<div class="logo">
				<a href="/">Sharely</a>
			</div>
			<div class="dynamic clearfix">
				<form id="searchForm" action="/Article/search/" method="get" accept-charset="utf-8">
					<div class="search">
							<input class="searchfield" type="text" name="search" placeholder="Produktsuche, z.B. Toaster, Schnautzbart">
							<span onclick="document.getElementById('searchForm').submit();" class="searchbutton glyph-search" value="send">
					</div>
				</form>
				<div class="navigation">
						<?php if (array_key_exists('username', $components)) echo $components['username']; ?>				
						<a href="/article/upload/"><span class="glyph-cog"></span></a> 		
				</div>
			</div>
			<div style="clear:both"></div>
		</div>
		<div id="bodysection">
			<div id="subnavigation">
				<?php echo $components['subnavigation']; ?>
			</div>

			<div id="content">
				<?php echo $components['content']; ?>
			</div>
		</div>
	</div>

</body>
</html>