<!DOCTYPE html>
<html>
<head>
	<title>Unser Webshop</title>
	<link rel="stylesheet" href="/css/css.css">
	<link rel="stylesheet" href="/css/reset.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="/js/js.js" type="text/javascript" charset="utf-8" async defer></script>
</head>
<body>
	<div id="page">
		<div id="header">
			<div class="logo">
				<a href="/"><img src="/images/logo.png" /></a>
			</div>
			<div class="dynamic clearfix">
				<div class="search">
						<input class="searchfield" type="text" name="search" placeholder="Produktsuche, z.B. Toaster, Schnautzbart">
						<span class="searchbutton glyph-search" value="send">
				</div>
				<div class="navigation">				
						<a href="settings.html"><span class="glyph-cog"></span></a> 		
				</div>

			</div>
		</div>
		<div id="bodysection">
			<div id="subnavigation">
				<ul class="level-1">
					<li>
						<span>Oberkategorie1</span>
						<ul class="level-2" toggled="false">
							<li><span>Unterkategorie1</span></li>
							<li><span>Unterkategorie2</span></li>
							<li><span>Unterkategorie3</span></li>
						</ul>
					</li>
					<li>
						<span>Oberkategorie2</span>
						<ul class="level-2" toggled="false">
							<li><span>Unterkategorie</span></li>
							<li><span>Unterkategorie2</span></li>
							<li><span>Unterkategorie3</span></li>
						</ul>
					</li>
					<li>
						<span>Oberkategorie3</span>
						<ul class="level-2">
							<li><span>Unterkategorie</span></li>
							<li><span>Unterkategorie2</span></li>
							<li><span>Unterkategorie3</span></li>
						</ul>
					</li>
				</ul>
			</div>

			<div id="content">
				<?php echo $components['content']; ?>
			</div>
		</div>
	</div>

</body>
</html>